[versions]
kotlinVersion = "1.6.10"
lifecycleVersion = "2.2.0"
androidAppCompatVersion = "1.2.0"
espressoCoreVersion = "3.2.0"
testRunnerVersion = "1.2.0"
testExtJunitVersion = "1.1.1"
playServicesLocationVersion = "18.0.0"
playServicesMapsVersion = "17.0.0"
googleMapsServicesVersion = "0.2.11"
mapboxVersion = "9.6.1"
mapboxNavigationVersion = "1.5.1"
mapboxAnnotationVersion = "0.9.0"
mapboxServicesVersion = "5.8.0"
multidexVersion = "2.0.1"
kotlinxSerializationVersion = "1.3.2"
coroutinesVersion = "1.6.0-native-mt"
ktorClientVersion = "1.6.7"
mokoGraphicsVersion = "0.9.0"
mokoParcelizeVersion = "0.8.0"
mokoResourcesVersion = "0.18.0"
mokoMvvmVersion = "0.12.0"
mokoGeoVersion = "0.5.0"
mokoPermissionsVersion = "0.11.0"
mokoMapsVersion = "0.7.0"

[libraries]
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidAppCompatVersion" }
lifecycle = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleVersion" }
playServicesLocation = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocationVersion" }
playServicesMaps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMapsVersion" }
googleMapsServices = { module = "com.google.maps:google-maps-services", version.ref = "googleMapsServicesVersion" }
mapbox = { module = "com.mapbox.mapboxsdk:mapbox-android-sdk", version.ref = "mapboxVersion" }
mapboxNavigation = { module = "com.mapbox.navigation:core", version.ref = "mapboxNavigationVersion" }
mapboxAnnotation = { module = "com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9", version.ref = "mapboxAnnotationVersion" }
mapboxServices = { module = "com.mapbox.mapboxsdk:mapbox-sdk-services", version.ref = "mapboxServicesVersion" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidexVersion" }
ktorClientOkHttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorClientVersion" }
kotlinSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationVersion" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesVersion" }
ktorClient = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientVersion" }

mokoResources = { module = "dev.icerock.moko:resources", version.ref = "mokoResourcesVersion" }
mokoParcelize = { module = "dev.icerock.moko:parcelize", version.ref = "mokoParcelizeVersion" }
mokoGraphics = { module = "dev.icerock.moko:graphics", version.ref = "mokoGraphicsVersion" }
mokoMvvmCore = { module = "dev.icerock.moko:mvvm-core", version.ref = "mokoMvvmVersion" }
mokoMvvmLiveData = { module = "dev.icerock.moko:mvvm-livedata", version.ref = "mokoMvvmVersion" }
mokoMvvmDataBinding = { module = "dev.icerock.moko:mvvm-databinding", version.ref = "mokoMvvmVersion" }
mokoGeo = { module = "dev.icerock.moko:geo", version.ref = "mokoGeoVersion" }
mokoPermissions = { module = "dev.icerock.moko:permissions", version.ref = "mokoPermissionsVersion" }
mokoMaps = { module = "dev.icerock.moko:maps", version.ref = "mokoMapsVersion" }
mokoMapsGoogle = { module = "dev.icerock.moko:maps-google", version.ref = "mokoMapsVersion" }
mokoMapsMapbox = { module = "dev.icerock.moko:maps-mapbox", version.ref = "mokoMapsVersion" }

kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlinVersion" }
ktorClientIos = { module = "io.ktor:ktor-client-ios", version.ref = "ktorClientVersion" }


kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }
androidGradlePlugin = { module = "com.android.tools.build:gradle", version = "7.0.4" }
googleServicesGradlePlugin = { module = "com.google.gms:google-services", version = "4.3.8" }
firebaseGradlePlugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version = "2.2.0" }
mokoGradlePlugin = { module = "dev.icerock.moko:moko-gradle-plugin", version = "0.1.0" }
mobileMultiplatformGradlePlugin = { module = "dev.icerock:mobile-multiplatform", version = "0.14.1" }
mokoResourcesGeneratorGradlePlugin = { module = "dev.icerock.moko:resources-generator", version.ref = "mokoResourcesVersion" }
kotlinSerializationGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlinVersion" }

